version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_motorcycles
    environment:
      POSTGRES_DB: motorcycles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
