version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: motorcyclesdb
    environment:
      POSTGRES_DB: motorcyclesdb
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
